[build]
target-dir = "target"

[alias]
bin = ["run", "--package", "cargo-bin", "--"]
build-all = ["build", "--workspace", "--all-targets", "--all-features"]
clippy-all = ["clippy", "--workspace", "--all-targets", "--all-features", "--", "-D", "warnings"]
fmt-check = ["fmt", "--all", "--", "--check"]
test-all = ["test", "--workspace", "--all-targets", "--all-features"]
